---
# tasks file for create-ec2-instances
- name: Create an instance
  block:
    - import_tasks: key-pair.yml
    - import_tasks: security-group.yml
    - import_tasks: ec2.yml
    - meta: refresh_inventory
    - pause:
        seconds: 30