- name: Get my public IP
  ipify_facts:

- name: Create Security Group
  ec2_group:
    name: "{{ instance_name }}-sg"
    description: Security Group for {{ instance_name }}
    vpc_id: "{{ vpc_id }}"
    region: "{{ region_name }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{ ipify_public_ip }}/32"
        rule_desc: "allow port 22 from {{ ipify_public_ip }}"
      - proto: tcp
        ports:
          - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: "allow for http access"
      - proto: tcp
        ports:
          - 3000
        cidr_ip: 0.0.0.0/0
        rule_desc: "allow for application"
  register: security_group