- name: SERVER | Add source for Nodejs
  shell: 'curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -'

- name: Install nodejs and npm
  vars:
    packages:
      - nodejs
  yum:
      name: "{{ packages }}"
